In [1]:
import pandas as pd
import numpy as np



In [5]:

arr = np.array([24, 53, 48, 47, 52, 39, 55, 35, 48, 31, 42, 30, 39, 45, 32])
print(arr)


[24 53 48 47 52 39 55 35 48 31 42 30 39 45 32]


In [6]:
arr[-5:-12:-1]

array([42, 31, 48, 35, 55, 39, 52])

In [7]:
b= np.random.randint(45, size=(5,5))
print(b)

[[ 0 30  1 43  9]
 [16 28  1 27  2]
 [ 0 39 39  2 41]
 [ 4 18 44 31  5]
 [25 27 29  9 24]]


In [8]:
b[-1]

array([25, 27, 29,  9, 24])

In [9]:
b[:,4]

array([ 9,  2, 41,  5, 24])

In [10]:
b[2,3]

2

In [11]:
np.random.seed(94)
b=np.random.randint(45,78,(7,8))
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [15]:
b[2] #2nd row

array([71, 56, 51, 58, 59, 47, 68, 77])

In [14]:
b[:,7] #7th column

array([53, 60, 77, 55, 51, 47, 61])

In [17]:
b[3,1]#3rd row,1st column

45

In [19]:
b[2,1:6]

array([56, 51, 58, 59, 47])

In [23]:
b[1:6:2]

array([[61, 59, 55, 77, 69, 69, 48, 60],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [75, 67, 53, 77, 60, 67, 67, 47]])

In [24]:
b[1:6:2,1:6]

array([[59, 55, 77, 69, 69],
       [45, 52, 74, 65, 53],
       [67, 53, 77, 60, 67]])

In [25]:
b[3:6,2:6]

array([[52, 74, 65, 53],
       [46, 69, 65, 75],
       [53, 77, 60, 67]])

In [26]:
b[1:6:2,1:8:3]

array([[59, 69, 60],
       [45, 65, 55],
       [67, 60, 47]])